// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateHostFile(arg1:string):Promise<view.HostFileInfo>;

export function DeleteHostFile(arg1:string):Promise<void>;

export function ListHostFiles():Promise<Array<view.HostFileInfo>>;

export function ReadHostFile(arg1:string):Promise<string>;

export function SaveHostFile(arg1:view.SaveHostFileRequest):Promise<void>;

export namespace view {
  export interface HostFileInfo {
    name: string;
    isDirty: boolean;
  }

  export interface SaveHostFileRequest {
    name: string;
    content: string;
  }
}
