// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Fuck(arg1) {
  return window['go']['view']['App']['Fuck'](arg1);
}

export function Greet(arg1) {
  return window['go']['view']['App']['Greet'](arg1);
}
