// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateHostFile(arg1) {
  return window['go']['view']['App']['CreateHostFile'](arg1);
}

export function DeleteHostFile(arg1) {
  return window['go']['view']['App']['DeleteHostFile'](arg1);
}

export function ListHostFiles() {
  return window['go']['view']['App']['ListHostFiles']();
}

export function ReadHostFile(arg1) {
  return window['go']['view']['App']['ReadHostFile'](arg1);
}

export function SaveHostFile(arg1) {
  return window['go']['view']['App']['SaveHostFile'](arg1);
}
