// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateHostFile(arg1:string):Promise<model.HostFileInfo>;

export function DeleteHostFile(arg1:string):Promise<void>;

export function ListHostFiles():Promise<Array<model.HostFileInfo>>;

export function ReadHostFile(arg1:string):Promise<string>;

export function SaveHostFile(arg1:model.SaveHostFileRequest):Promise<void>;
