// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateHostFile(arg1) {
  return window['go']['view']['Hosts']['CreateHostFile'](arg1);
}

export function DeleteHostFile(arg1) {
  return window['go']['view']['Hosts']['DeleteHostFile'](arg1);
}

export function ListHostFiles() {
  return window['go']['view']['Hosts']['ListHostFiles']();
}

export function ReadHostFile(arg1) {
  return window['go']['view']['Hosts']['ReadHostFile'](arg1);
}

export function SaveHostFile(arg1) {
  return window['go']['view']['Hosts']['SaveHostFile'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['view']['Hosts']['SetCtx'](arg1);
}
