# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link: "mysql:root:JKLjkl@2023#@tcp(host.docker.internal:13306)/host-editor?charset=utf8mb4&parseTime=true&loc=Local"
        tables: ""
        jsonCase: "CamelLower"
        group: "default"
        descriptionTag: true
